# Generated by Django 6.0.4 on 2026-04-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=255, verbose_name='Title (KK)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_kk', models.TextField(blank=True, verbose_name='Content (KK)')),
                ('content_ru', models.TextField(blank=True, verbose_name='Content (RU)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (EN)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='applicants.menu', verbose_name='Parent menu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
